name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "main", "master", "prod" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * 5"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup default nightly 
          rustup target add wasm32-unknown-unknown --toolchain nightly
          npm install -g wasm-pack
      - name: build
        run: cargo build --workspace --release --target wasm32-unknown-unknown && npm run build
      - name: test
        run: npm run test
  apps:
    if: ${{ github.event.inputs.publish }}
    name: Publish
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - template-sveltekit-wasm
    steps:
      - uses: actions/checkout@v3
      - run: cargo xtask setup
      - name: Publish (${{ matrix.package }})
        run: cargo publish --all-features -v -p ${{ matrix.package }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  